# Basic Tutorial 2

This tutorial instructs how to a simple model, feed data to train and evaluate the model.

In [1]:
import numpy as np
import tensorflow as tf
from tensorflow.python.keras import layers

## Construct the model

Define model and its layers.

In [2]:
model = tf.keras.Sequential()

# create a fully-connected layer with 64 hidden units
model.add(layers.Dense(64, activation='relu', input_shape=(32,)))
model.add(layers.Dense(64, activation='relu'))

# create softmax layer with 10 output units
model.add(layers.Dense(10, activation='softmax'))

# print model
print(model.summary())

Instructions for updating:
Colocations handled automatically by placer.
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 64)                2112      
_________________________________________________________________
dense_1 (Dense)              (None, 64)                4160      
_________________________________________________________________
dense_2 (Dense)              (None, 10)                650       
Total params: 6,922
Trainable params: 6,922
Non-trainable params: 0
_________________________________________________________________
None


After the model is constructed, set learning process by calling .compile method.

There are 3 import arguments in .compile:
- optimizer: set optimization schemes for training procedure, such as Adam, RMSProp or Gradient descent.
- loss: set loss function to minimize during optimization, such as mean squared error, cross entropy.
- metrics: used to monitor training process.

In [3]:
# compile the model with Adam optimizer and categorical cross entropy loss function.
model.compile(optimizer=tf.train.AdamOptimizer(0.01), 
              loss='categorical_crossentropy',
              metrics=['accuracy'])

## Input data

To create small dataset, NumPy arrays are used to train and validate model during training.

In [5]:
train_data = np.random.random(size=(1000, 32))
train_labels = np.random.random(size=(1000, 10))

val_data = np.random.random(size=(100, 32))
val_labels = np.random.random(size=(100, 10))

## Training model

The model is "fit" to training data using fit method.

fit method has 3 important arguments:
- epochs: set training epochs. n epoch is one iteration over the entire input data.
- batch_size: the model slices the data into smaller batches and iterates over these batches during training.
- validation_data: to validate performance of model after finishing each epoch.

In [6]:
model.fit(train_data, train_labels, batch_size=32, epochs=10, validation_data=(val_data, val_labels))

Train on 1000 samples, validate on 100 samples
Instructions for updating:
Use tf.cast instead.
Epoch 1/10
1000/1000 [==============================] - 0s 309us/sample - loss: 11.5571 - acc: 0.0790 - val_loss: 11.5468 - val_acc: 0.0900
Epoch 2/10
1000/1000 [==============================] - 0s 81us/sample - loss: 11.5224 - acc: 0.1000 - val_loss: 11.5502 - val_acc: 0.1000
Epoch 3/10
1000/1000 [==============================] - 0s 84us/sample - loss: 11.5207 - acc: 0.1050 - val_loss: 11.5492 - val_acc: 0.1200
Epoch 4/10
1000/1000 [==============================] - 0s 81us/sample - loss: 11.5188 - acc: 0.1050 - val_loss: 11.5519 - val_acc: 0.0600
Epoch 5/10
1000/1000 [==============================] - 0s 77us/sample - loss: 11.5185 - acc: 0.1040 - val_loss: 11.5523 - val_acc: 0.1100
Epoch 6/10
1000/1000 [==============================] - 0s 82us/sample - loss: 11.5180 - acc: 0.1010 - val_loss: 11.5545 - val_acc: 0.1100
Epoch 7/10
1000/1000 [==============================] - 0s 90us/sample

## Evaluate and predict

After training model, we should evaluate the model with a secret data set to make sure the model work in practice.

Create evaluate/test data.

In [7]:
test_data = np.random.random(size=(1000, 32))
test_labels = np.random.random(size=(1000, 10))

Evaluate the model.

In [8]:
model.evaluate(test_data, test_labels, batch_size=32)

1000/1000 [==============================] - 0s 45us/sample - loss: 11.3924 - acc: 0.1100


[11.392366744995117, 0.11]

evaluate method returns loss and metric values in test_data. In this case, the trained model is not good on evaluate data!

To predict output in inference for provided data, we use predict method

In [9]:
result = model.predict(test_data, batch_size=32)
# predict result
print('Predict:\n', result)
print('Ground Truth:\n', test_labels)


Predict:
 [[0.1042226  0.09494346 0.09819039 ... 0.09827932 0.10280883 0.09879021]
 [0.10430711 0.09523211 0.09812328 ... 0.0980639  0.1028681  0.09887344]
 [0.10926478 0.09286349 0.09677936 ... 0.09483537 0.10499472 0.09886053]
 ...
 [0.10230422 0.09589709 0.09976564 ... 0.09821642 0.10377233 0.10037734]
 [0.10594976 0.09942362 0.09996614 ... 0.09475022 0.10502539 0.0972486 ]
 [0.10529609 0.09890055 0.09809931 ... 0.09694751 0.10048994 0.10194965]]
Ground Truth:
 [[0.85717718 0.32515428 0.70824328 ... 0.77010175 0.05002063 0.57352445]
 [0.02431494 0.67259209 0.2074535  ... 0.16639488 0.75928947 0.5540413 ]
 [0.37413992 0.57201891 0.54382188 ... 0.65805378 0.89273681 0.71762163]
 ...
 [0.38400491 0.86842231 0.7142257  ... 0.95321027 0.24023026 0.09423668]
 [0.28428124 0.10532911 0.45218222 ... 0.18050735 0.84049514 0.59523884]
 [0.86560028 0.12663666 0.80414023 ... 0.30301556 0.64176889 0.39584418]]
